const KEY='shiftly-v1';
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const uid=()=>Date.now().toString(36)+Math.random().toString(36).slice(2,7);
const initial={event:{name:'',date:'',start:'09:00',end:'17:00'},slots:[],people:[],rules:{maxShifts:2,leaderRequired:true},schedule:null};
let state=load();
function load(){try{return {...structuredClone(initial),...JSON.parse(localStorage.getItem(KEY)||'{}')}}catch{return structuredClone(initial)}}
function save(){localStorage.setItem(KEY,JSON.stringify(state));renderStats()}
function esc(s){return String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function slotLabel(s){return `${s.start}–${s.end}`}
function setMessage(text,type='error'){const el=$('#message');el.className=`message ${type}`;el.innerHTML=text}
function clearMessage(){$('#message').className='message';$('#message').textContent=''}
function syncInputs(){const e=state.event;$('#eventName').value=e.name||'';$('#eventDate').value=e.date||'';$('#dayStart').value=e.start||'';$('#dayEnd').value=e.end||'';$('#maxShifts').value=state.rules.maxShifts;$('#leaderRequired').checked=state.rules.leaderRequired}
function renderStats(){$('#heroPeople').textContent=state.people.length;$('#heroSlots').textContent=state.slots.length}
function renderSlots(){const body=$('#slotsBody');body.innerHTML=state.slots.map((s,i)=>`<tr><td>${esc(s.date)}</td><td>${esc(s.start)}</td><td>${esc(s.end)}</td><td>${s.need} 人</td><td><button class="icon-btn edit-slot" data-id="${s.id}" title="編輯">✎</button> <button class="icon-btn danger-btn delete-slot" data-id="${s.id}" title="刪除">×</button></td></tr>`).join('');$('#slotsEmpty').classList.toggle('hide',state.slots.length>0);$('.table-wrap').classList.toggle('hide',!state.slots.length)}
function renderPeople(){const grid=$('#peopleGrid');grid.innerHTML=state.people.map(p=>{const available=state.slots.filter(s=>p.availability.includes(s.id)).map(slotLabel);return `<article class="person-card"><div class="person-top"><span class="avatar">${esc(p.name.slice(0,1).toUpperCase())}</span><span class="card-actions"><button class="icon-btn edit-person" data-id="${p.id}">✎</button><button class="icon-btn danger-btn delete-person" data-id="${p.id}">×</button></span></div><h3>${esc(p.name)} ${p.leader?'<span class="leader-tag">組長</span>':''}</h3><p>${available.length?available.map(esc).join('・'):'未設定可值班時段'}</p></article>`}).join('');$('#peopleEmpty').classList.toggle('hide',state.people.length>0)}
function render(){syncInputs();renderStats();renderSlots();renderPeople();renderResult()}
function invalidate(){state.schedule=null;save();renderResult()}
['eventName','eventDate','dayStart','dayEnd'].forEach(id=>$('#'+id).addEventListener('change',e=>{const map={eventName:'name',eventDate:'date',dayStart:'start',dayEnd:'end'};state.event[map[id]]=e.target.value;save()}));
$('#maxShifts').addEventListener('change',e=>{state.rules.maxShifts=Math.max(1,+e.target.value||1);invalidate()});
$('#leaderRequired').addEventListener('change',e=>{state.rules.leaderRequired=e.target.checked;invalidate()});
function openSlot(id=''){const s=state.slots.find(x=>x.id===id);$('#slotDialogTitle').textContent=s?'修改時段':'新增時段';$('#slotId').value=s?.id||'';$('#slotDate').value=s?.date||state.event.date||new Date().toISOString().slice(0,10);$('#slotStart').value=s?.start||state.event.start||'09:00';$('#slotEnd').value=s?.end||state.event.end||'11:00';$('#slotNeed').value=s?.need||2;$('#slotDialog').showModal()}
$('#addSlotBtn').onclick=()=>openSlot();
const slotPresets={full:[['09:00','11:00'],['11:00','13:00'],['13:00','15:00'],['15:00','17:00']],morning:[['08:00','10:00'],['10:00','12:00']],afternoon:[['13:00','15:00'],['15:00','17:00']],hourly:[['09:00','10:00'],['10:00','11:00'],['11:00','12:00'],['12:00','13:00'],['13:00','14:00'],['14:00','15:00'],['15:00','16:00'],['16:00','17:00']]};
$$('.preset-btn').forEach(btn=>btn.addEventListener('click',()=>{const date=state.event.date||new Date().toISOString().slice(0,10);const preset=slotPresets[btn.dataset.preset];const fresh=preset.filter(([start,end])=>!state.slots.some(s=>s.date===date&&s.start===start&&s.end===end));if(!fresh.length)return setMessage('這組常用時段已經全部加入。');fresh.forEach(([start,end])=>state.slots.push({id:uid(),date,start,end,need:2}));state.slots.sort((a,b)=>(a.date+a.start).localeCompare(b.date+b.start));invalidate();renderSlots();renderPeople();clearMessage();setMessage(`已加入 ${fresh.length} 個常用值班時段，預設需求為 2 人。`,'success')}));
$('#slotForm').addEventListener('submit',e=>{e.preventDefault();const data={id:$('#slotId').value||uid(),date:$('#slotDate').value,start:$('#slotStart').value,end:$('#slotEnd').value,need:+$('#slotNeed').value};if(data.start>=data.end)return alert('結束時間必須晚於開始時間。');if(data.need<1)return alert('需求人數至少為 1。');const idx=state.slots.findIndex(s=>s.id===data.id);if(idx>=0)state.slots[idx]=data;else state.slots.push(data);state.slots.sort((a,b)=>(a.date+a.start).localeCompare(b.date+b.start));invalidate();renderSlots();renderPeople();$('#slotDialog').close()});
function openPerson(id=''){if(!state.slots.length)return setMessage('請先建立至少一個值班時段，再新增人員。');const p=state.people.find(x=>x.id===id);$('#personDialogTitle').textContent=p?'修改人員':'新增人員';$('#personId').value=p?.id||'';$('#personName').value=p?.name||'';$('#personLeader').checked=!!p?.leader;$('#availabilityList').innerHTML=state.slots.map((s,i)=>`<label class="availability-option"><input type="checkbox" value="${s.id}" ${p?.availability.includes(s.id)?'checked':''}><span>${esc(s.date)} ${esc(slotLabel(s))}</span></label>`).join('');$('#personDialog').showModal()}
$('#addPersonBtn').onclick=()=>openPerson();
$('#personForm').addEventListener('submit',e=>{e.preventDefault();const name=$('#personName').value.trim();if(!name)return;const id=$('#personId').value||uid();if(state.people.some(p=>p.name.toLowerCase()===name.toLowerCase()&&p.id!==id))return alert('人員姓名不可重複。');const p={id,name,leader:$('#personLeader').checked,availability:$$('#availabilityList input:checked').map(x=>x.value)};const idx=state.people.findIndex(x=>x.id===id);if(idx>=0)state.people[idx]=p;else state.people.push(p);invalidate();renderPeople();$('#personDialog').close()});
document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;const id=b.dataset.id;if(b.classList.contains('edit-slot'))openSlot(id);if(b.classList.contains('delete-slot')){if(confirm('刪除此時段？人員的相關可值班設定也會一併移除。')){state.slots=state.slots.filter(s=>s.id!==id);state.people.forEach(p=>p.availability=p.availability.filter(x=>x!==id));invalidate();renderSlots();renderPeople()}}if(b.classList.contains('edit-person'))openPerson(id);if(b.classList.contains('delete-person')){if(confirm('確定刪除此人員？')){state.people=state.people.filter(p=>p.id!==id);invalidate();renderPeople()}}if(b.classList.contains('close-dialog'))b.closest('dialog').close();if(b.classList.contains('remove-person'))manualRemove(b.dataset.slot,b.dataset.person)});
function validate(){if(!state.slots.length)return '請先建立至少一個值班時段。';if(!state.people.length)return '請先新增至少一位工作人員。';for(const s of state.slots){if(!s.date||!s.start||!s.end||s.start>=s.end||s.need<1)return `${slotLabel(s)} 的設定不正確。`;const avail=state.people.filter(p=>p.availability.includes(s.id));if(avail.length<s.need)return `${slotLabel(s)} 需要 ${s.need} 位工作人員，但只有 ${avail.length} 位可以值班。`;if(state.rules.leaderRequired&&!avail.some(p=>p.leader))return `${slotLabel(s)} 要求至少一位組長，但沒有任何組長可以值班。`}const need=state.slots.reduce((n,s)=>n+s.need,0);if(state.people.length*state.rules.maxShifts<need)return `在「每人最多 ${state.rules.maxShifts} 個時段」的限制下，總容量不足（需要 ${need} 人次，最多只能安排 ${state.people.length*state.rules.maxShifts} 人次）。`;return ''}
function combinations(arr,k){const out=[];function go(start,pick){if(pick.length===k){out.push([...pick]);return}for(let i=start;i<=arr.length-(k-pick.length);i++){pick.push(arr[i]);go(i+1,pick);pick.pop()}}go(0,[]);return out}
function solve(){const err=validate();if(err)return {error:err};const counts=Object.fromEntries(state.people.map(p=>[p.id,0]));const assignment={};const ordered=[...state.slots].sort((a,b)=>state.people.filter(p=>p.availability.includes(a.id)).length-a.need-(state.people.filter(p=>p.availability.includes(b.id)).length-b.need));let nodes=0;function search(i){if(++nodes>350000)return false;if(i===ordered.length)return true;const s=ordered[i];const candidates=state.people.filter(p=>p.availability.includes(s.id)&&counts[p.id]<state.rules.maxShifts);let combos=combinations(candidates,s.need).filter(c=>!state.rules.leaderRequired||c.some(p=>p.leader));combos.sort((a,b)=>a.reduce((n,p)=>n+counts[p.id]**2,0)-b.reduce((n,p)=>n+counts[p.id]**2,0)+Math.random()*.001);for(const c of combos){assignment[s.id]=c.map(p=>p.id);c.forEach(p=>counts[p.id]++);if(search(i+1))return true;c.forEach(p=>counts[p.id]--);delete assignment[s.id]}return false}return search(0)?{assignment}:{error:'找不到同時符合所有限制的安排。請增加可值班人員、提高每人最大值班量，或調整組長需求。'}}
function generate(){clearMessage();if(state.schedule&&!confirm('重新排班會覆蓋目前結果與手動調整，是否繼續？'))return;const result=solve();if(result.error){state.schedule=null;save();renderResult();setMessage(`⚠ 無法產生符合目前條件的班表。<br>${esc(result.error)}`);return}state.schedule=result.assignment;save();renderResult();setMessage('✓ 班表已成功產生，所有必要限制皆已滿足。','success');$('#result').scrollIntoView({behavior:'smooth'})}
$('#generateBtn').onclick=generate;$('#generateTopBtn').onclick=generate;
function scheduleCounts(){const c=Object.fromEntries(state.people.map(p=>[p.id,0]));Object.values(state.schedule||{}).flat().forEach(id=>{if(id in c)c[id]++});return c}
function renderResult(){const section=$('#result');if(!state.schedule){section.hidden=true;return}section.hidden=false;$('#resultEvent').textContent=state.event.name||'未命名活動';$('#resultDate').textContent=state.event.date||state.slots[0]?.date||'—';const counts=scheduleCounts();$('#scheduleList').innerHTML=state.slots.map(s=>{const ids=state.schedule[s.id]||[];const assigned=ids.map(id=>state.people.find(p=>p.id===id)).filter(Boolean);const options=state.people.filter(p=>!ids.includes(p.id)).map(p=>`<option value="${p.id}">${esc(p.name)}${p.leader?'（組長）':''}</option>`).join('');return `<div class="schedule-row"><div class="schedule-time"><strong>${esc(slotLabel(s))}</strong><small>${esc(s.date)} · 需求 ${s.need} 人</small></div><div class="chips">${assigned.map(p=>`<span class="chip ${p.leader?'leader':''}">${esc(p.name)}${p.leader?' ♛':''}<button class="remove-person" data-slot="${s.id}" data-person="${p.id}" title="移除">×</button></span>`).join('')}</div><select class="add-select" data-slot="${s.id}"><option value="">＋ 加入人員</option>${options}</select></div>`}).join('');const max=Math.max(1,...Object.values(counts));$('#workloadList').innerHTML=state.people.map(p=>`<div class="workload-row"><span>${esc(p.name)}${p.leader?' ♛':''}</span><b>${counts[p.id]} 個</b><span class="bar"><i style="width:${counts[p.id]/max*100}%"></i></span></div>`).join('')}
$('#scheduleList').addEventListener('change',e=>{if(e.target.matches('.add-select')&&e.target.value)manualAdd(e.target.dataset.slot,e.target.value)});
function manualRemove(slotId,personId){const s=state.slots.find(x=>x.id===slotId);if((state.schedule[slotId]||[]).length<=s.need&&!confirm('移除後將低於此時段的需求人數。仍要移除嗎？'))return;const remaining=state.schedule[slotId].filter(id=>id!==personId);if(state.rules.leaderRequired&&!remaining.some(id=>state.people.find(p=>p.id===id)?.leader)&&!confirm('移除後此時段將沒有組長。仍要移除嗎？'))return;state.schedule[slotId]=remaining;save();renderResult()}
function manualAdd(slotId,personId){const s=state.slots.find(x=>x.id===slotId),p=state.people.find(x=>x.id===personId),counts=scheduleCounts();if(!p.availability.includes(slotId))return alert(`${p.name} 在 ${slotLabel(s)} 無法值班。`);if(counts[personId]>=state.rules.maxShifts)return alert(`${p.name} 已達每人最多 ${state.rules.maxShifts} 個時段的限制。`);if(state.schedule[slotId].length>=s.need&&!confirm('此時段已達需求人數，加入後會超額。仍要加入嗎？'))return;state.schedule[slotId].push(personId);save();renderResult()}
$('#demoBtn').onclick=()=>{if((state.slots.length||state.people.length)&&!confirm('載入範例會取代目前資料，是否繼續？'))return;const date=new Date();date.setDate(date.getDate()+1);const d=date.toISOString().slice(0,10);const slots=[['09:00','11:00',2],['11:00','13:00',3],['13:00','15:00',3],['15:00','17:00',2]].map((x,i)=>({id:'s'+(i+1),date:d,start:x[0],end:x[1],need:x[2]}));const all=slots.map(s=>s.id);const specs=[['Alice',1,[0,1]],['Bob',0,[1,2,3]],['Carol',0,[0,2]],['David',1,[0,1,2,3]],['Eve',0,[0,3]],['Frank',0,[1,2]],['Grace',1,[0,2,3]],['Henry',0,[1,2,3]]];state={event:{name:'2026 AI Workshop',date:d,start:'09:00',end:'17:00'},slots,people:specs.map(([name,leader,idx])=>({id:uid(),name,leader:!!leader,availability:idx.map(i=>all[i])})),rules:{maxShifts:2,leaderRequired:true},schedule:null};save();render();clearMessage();setMessage('範例資料已載入。按下「產生班表」即可查看結果。','success')};
$('#csvBtn').onclick=()=>{if(!state.slots.length)return setMessage('請先建立時段，再匯入人員。');$('#csvError').textContent='';$('#csvDialog').showModal()};
function buildSampleCsv(){const total=state.slots.length;if(!total)return '';const patterns=[[1,2],[2,3,4],[1,3],[1,2,3,4],[1,4],[2,3],[1,3,4],[2,3,4]],names=[['Alice','是'],['Bob','否'],['Carol','否'],['David','是'],['Eve','否'],['Frank','否'],['Grace','是'],['Henry','否']];const rows=names.map(([name,leader],i)=>{let slots=patterns[i].filter(n=>n<=total);if(!slots.length)slots=[i%total+1];return `${name},${leader},${slots.join('|')}`});return ['姓名,是否為組長,可值班時段',...rows].join('\n')}
$('#sampleCsvBtn').onclick=()=>{const csv=buildSampleCsv();if(!csv)return setMessage('請先建立至少一個時段，再下載範例 CSV。');download('人員管理範例.csv',csv)};
$('#fillSampleCsvBtn').onclick=()=>{const csv=buildSampleCsv();if(!csv){$('#csvError').textContent='請先建立至少一個值班時段。';return}$('#csvText').value=csv;$('#csvError').textContent=`已依目前的 ${state.slots.length} 個時段產生範例，可以直接匯入。`};
function parseCsvLine(line){const out=[];let cur='',quote=false;for(let i=0;i<line.length;i++){const c=line[i];if(c==='"'&&line[i+1]==='"'){cur+='"';i++}else if(c==='"')quote=!quote;else if(c===','&&!quote){out.push(cur.trim());cur=''}else cur+=c}out.push(cur.trim());return out}
$('#csvForm').addEventListener('submit',e=>{e.preventDefault();const lines=$('#csvText').value.trim().split(/\r?\n/).filter(Boolean);if(lines.length<2){$('#csvError').textContent='CSV 至少需要標題列與一筆資料。';return}const imported=[];for(let i=1;i<lines.length;i++){const [name,lead,avail]=parseCsvLine(lines[i]);if(!name){$('#csvError').textContent=`第 ${i+1} 列缺少姓名。`;return}const tokens=(avail||'').split('|').map(x=>x.trim()).filter(Boolean);const ids=tokens.map(t=>{if(/^\d+$/.test(t))return state.slots[+t-1]?.id;const norm=t.replace('–','-');return state.slots.find(s=>`${s.start}-${s.end}`===norm)?.id}).filter(Boolean);if(tokens.length!==ids.length){$('#csvError').textContent=`第 ${i+1} 列含有找不到的時段。請使用時段編號或 HH:MM-HH:MM。`;return}imported.push({id:uid(),name,leader:/^(是|true|1|yes|y)$/i.test(lead),availability:ids})}state.people.push(...imported);invalidate();renderPeople();$('#csvDialog').close();setMessage(`已成功匯入 ${imported.length} 位人員。`,'success')});
function download(name,text,type='text/csv;charset=utf-8'){const blob=new Blob(['\ufeff'+text],{type});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;a.click();URL.revokeObjectURL(a.href)}
$('#downloadTemplateBtn').onclick=()=>download('人員匯入空白範本.csv','姓名,是否為組長,可值班時段\n王小明,是,1|2');
$('#exportBtn').onclick=()=>{if(!state.schedule)return;const rows=[['日期','開始時間','結束時間','人員姓名','是否為組長']];state.slots.forEach(s=>(state.schedule[s.id]||[]).forEach(id=>{const p=state.people.find(x=>x.id===id);if(p)rows.push([s.date,s.start,s.end,p.name,p.leader?'是':'否'])}));download(`${state.event.name||'值班表'}.csv`,rows.map(r=>r.map(v=>`"${String(v).replaceAll('"','""')}"`).join(',')).join('\n'))};
$('#printBtn').onclick=()=>window.print();render();
